### ISSUE TITLE
Error using scoop on example data

### ISSUE THREAD

**Issue by charleygros** [neuropoly/template#3]
***Issue:***
Error when running the last step of the SOP using the example data:
```
python -m scoop -n 5 -vvv generate_template.py
```

***Environment:***
- SCT v3.2.4.
- scoop v0.7.1.1
- OS: Ubuntu 16.04
- as suggested in the SOP, I removed all the parameter names `scoop.futures:submit()` of the file `nist_mni_pipelines/ipl/model/generate_nonlinear.py` --> is it correct? I am somehow scared that the error is coming from here.
- My bashrc:
```
export PYTHONPATH="${PYTHONPATH}:/home/charley/nist_mni_pipelines"
export PYTHONPATH="${PYTHONPATH}:/home/charley/nist_mni_pipelines/ipl/"
export PYTHONPATH="${PYTHONPATH}:/home/charley/nist_mni_pipelines/ipl"
```

***Error message:***
```
[2018-09-10 17:01:36,990] launcher  INFO    SCOOP 0.7 1.1 on linux2 using Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)], API: 1013
[2018-09-10 17:01:36,991] launcher  INFO    Deploying 2 worker(s) over 1 host(s).
[2018-09-10 17:01:36,991] launcher  DEBUG   Using hostname/ip: "127.0.0.1" as external broker reference.
[2018-09-10 17:01:36,991] launcher  DEBUG   The python executable to execute the program with is: /home/charley/spinalcordtoolbox/python/bin/python.
[2018-09-10 17:01:36,991] launcher  INFO    Worker distribution: 
[2018-09-10 17:01:36,991] launcher  INFO       127.0.0.1:	1 + origin
[2018-09-10 17:01:37,007] brokerLaunch (127.0.0.1:40605) DEBUG   Local broker launched on ports 40605, 42639.
[2018-09-10 17:01:37,007] launcher  (127.0.0.1:40605) DEBUG   Initialising local worker 2 [127.0.0.1].
[2018-09-10 17:01:37,007] launcher  (127.0.0.1:40605) DEBUG   Initialising local origin worker 1 [127.0.0.1].
[2018-09-10 17:01:37,007] launcher  (127.0.0.1:40605) DEBUG   127.0.0.1: Launching '(/home/charley/spinalcordtoolbox/python/bin/python -m scoop.bootstrap.__main__ --size 2 --workingDirectory /home/charley/code/exvivo_atlas/template --brokerHostname 127.0.0.1 --externalBrokerHostname 127.0.0.1 --taskPort 40605 --metaPort 42639 --backend=ZMQ -v generate_template.py & ) && (/home/charley/spinalcordtoolbox/python/bin/python -m scoop.bootstrap.__main__ --size 2 --workingDirectory /home/charley/code/exvivo_atlas/template --brokerHostname 127.0.0.1 --externalBrokerHostname 127.0.0.1 --taskPort 40605 --metaPort 42639 --origin --backend=ZMQ -v generate_template.py)'
ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsFV2y7C/EqmXyFflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[2018-09-10 17:01:37,164] _control  (127.0.0.1:58866) DEBUG   The following error occurend on a worker:
mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]
Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py", line 127, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/home/charley/nist_mni_pipelines/ipl/model/filter.py", line 14, in generate_flip_sample
    m.flip_volume_x(input.scan,input.scan_f)
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 1111, in flip_volume_x
    scales=[-1.0,1.0,1.0])
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 1103, in param2xfm
    self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 416, in command
    raise mincError("ERROR: command {} Error:{}!\nMessage: {}\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))
mincError: mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]

[2018-09-10 17:01:37,164] _control  (127.0.0.1:61547) DEBUG   The following error occurend on a worker:
mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsFV2y7C/EqmXyFflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]
Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py", line 127, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/home/charley/nist_mni_pipelines/ipl/model/filter.py", line 14, in generate_flip_sample
    m.flip_volume_x(input.scan,input.scan_f)
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 1111, in flip_volume_x
    scales=[-1.0,1.0,1.0])
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 1103, in param2xfm
    self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 416, in command
    raise mincError("ERROR: command {} Error:{}!\nMessage: {}\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))
mincError: mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsFV2y7C/EqmXyFflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]

[2018-09-10 17:01:37,166] _control  (127.0.0.1:61547) DEBUG   The following error occurend on a worker:
mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]
Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py", line 127, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "generate_template.py", line 21, in <module>
    'refine': True
  File "/home/charley/nist_mni_pipelines/ipl/model/generate_nonlinear.py", line 314, in generate_nonlinear_model_csv
    return generate_nonlinear_average(internal_sample,internal_model,prefix=work_prefix,options=options,skip=skip,stop_early=stop_early)
  File "/home/charley/nist_mni_pipelines/ipl/model/generate_nonlinear.py", line 91, in generate_nonlinear_average
    futures.wait(flip_all, return_when=futures.ALL_COMPLETED)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/futures.py", line 391, in wait
    for _ in _waitAll(*fs):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/futures.py", line 358, in _waitAll
    for f in _waitAny(future):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/futures.py", line 335, in _waitAny
    raise childFuture.exceptionValue
mincError: mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]

ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsJUiLA2/eHSVLpflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[2018-09-10 17:01:37,169] _control  (127.0.0.1:58866) DEBUG   The following error occurend on a worker:
mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsJUiLA2/eHSVLpflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]
Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py", line 127, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/home/charley/nist_mni_pipelines/ipl/model/filter.py", line 14, in generate_flip_sample
    m.flip_volume_x(input.scan,input.scan_f)
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 1111, in flip_volume_x
    scales=[-1.0,1.0,1.0])
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 1103, in param2xfm
    self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 416, in command
    raise mincError("ERROR: command {} Error:{}!\nMessage: {}\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))
mincError: mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsJUiLA2/eHSVLpflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]

Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 290, in run
    futures_startup()
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 271, in futures_startup
    run_name="__main__"
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/futures.py", line 64, in _startup
    result = _controller.switch(rootFuture, *args, **kargs)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py", line 253, in runController
    raise future.exceptionValue
ipl.minc_tools.mincError: mincError:ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
Message: 
Traceback (most recent call last):
  File "/home/charley/nist_mni_pipelines/ipl/minc_tools.py", line 407, in command
    p=subprocess.Popen(cmds, stdout=fnull, stderr=subprocess.PIPE,shell=use_shell)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/charley/spinalcordtoolbox/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

AT:[('/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/scoop/_control.py', 127, 'runFuture', 'future.resultValue = future.callable(*future.args, **future.kargs)'), ('/home/charley/nist_mni_pipelines/ipl/model/filter.py', 14, 'generate_flip_sample', 'm.flip_volume_x(input.scan,input.scan_f)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1111, 'flip_volume_x', 'scales=[-1.0,1.0,1.0])'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 1103, 'param2xfm', 'self.command(cmd, inputs=[], outputs=[output], verbose=self.verbose)'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 416, 'command', 'raise mincError("ERROR: command {} Error:{}!\\nMessage: {}\\n{}".format(str(cmds),str(outvalue),output_stderr,traceback.format_exc()))'), ('/home/charley/nist_mni_pipelines/ipl/minc_tools.py', 64, '__init__', 'self.stack = traceback.extract_stack()')]
[2018-09-10 17:01:37,500] launcher  (127.0.0.1:40605) INFO    Root process is done.
[2018-09-10 17:01:37,501] workerLaunch (127.0.0.1:40605) DEBUG   Closing workers on 127.0.0.1 (2 workers).
[2018-09-10 17:01:37,501] brokerLaunch (127.0.0.1:40605) DEBUG   Closing local broker.
[2018-09-10 17:01:37,501] launcher  (127.0.0.1:40605) INFO    Finished cleaning spawned subprocesses.
```

**Comment by jcohenadad** [comment]
hum, i'm wondering if this is caused by `nist_mni_pipelines/ipl/model/generate_nonlinear.py` indeed. @benjamindeleener do you have any tips for us?

**Comment by benjamindeleener** [comment]
@charleygros @jcohenadad the error seems to be initiated with the command `param2xfm` as one of the first line shows:
```
ERROR: command ['param2xfm', '-clobber', '/tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm', '-scales', '-1.0', '1.0', '1.0'] Error:0!
```

Could you try to run this command: 
```
param2xfm -clobber /tmp/iplMincToolsMegAoO/8whQFOflip_x.xfm -scales -1.0 1.0 1.0
```

I am not sure it is gonna find the temp files, but my guess would be that the file was originally not present, so I would try to go back to the output folder and check if the flip files were correctly created.
The error could also come from a memory issue or a permission issue.

**Comment by jcohenadad** [comment]
@charleygros Is this issue fixed?
